name: CI Pipeline

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

jobs:
    code-quality:
        name: Code Quality Checks
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20] # Start with Node 20, expand later

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Check code formatting
              run: npm run format

            - name: Run linter
              run: npm run lint

            - name: TypeScript type check
              run: npx tsc --noEmit

            - name: Build project
              run: npm run build

    test:
        name: Run Tests
        runs-on: ubuntu-latest
        needs: code-quality # Run after code quality passes

        env:
            NODE_ENV: test
            DB_HOST: localhost
            DB_USERNAME: oalr
            DB_PASSWORD: oalr123
            DB_NAME: oalr_test
            JWT_SECRET_KEY: test-jwt-secret-for-ci-only
            GOOGLE_CLIENT_ID: test-google-client-id
            GOOGLE_CLIENT_SECRET: test-google-client-secret

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Run unit tests
              run: npm run test -- --coverage --watchAll=false
